# Generated by Django 4.2 on 2024-10-17 20:59

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conference_capacity_alter_conference_program_and_more'),
        ('users', '0002_participant_reservations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='cin',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='This field must contain exactly 8 digits', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[users.models.email_validator]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='reservations',
            field=models.ManyToManyField(related_name='reservations', through='users.Reservation', to='conferences.conference'),
        ),
    ]
