# Generated by Django 4.2 on 2024-10-18 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_alter_conference_capacity_alter_conference_program_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='the start date must be grater or equal than today',
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 18))), name='the start date must be grater or equal than today'),
        ),
    ]
